### PR TITLE
Automatic release part 2

### PR DESCRIPTION
**Pull request by dvviktordelev**
closes https://github.com/datavisyn/infrastructure-k8s/issues/319#issuecomment-2454523041

### CODE REVIEW

**Review by dvvanessastoiber — CHANGES_REQUESTED** [review]
@dvviktordelev Thank you for implementing the feedback! I just tested the workflow and it fails due to an issue parsing the JSON: https://github.com/datavisyn/test-app/actions/runs/11802941712/job/32879764274. Please take another look at this. Thank you!

**Comment by dvviktordelev** [comment]
@dvvanessastoiber fix committed

**Comment by dvvanessastoiber** [comment]
> @dvvanessastoiber fix committed

Thanks @dvviktordelev! We still have the same issue unfortunately: https://github.com/datavisyn/test-app/actions/runs/11803159213/job/32880501231 (the tag is created correctly but not the Github Release). And the build succeeds although I would expect it to fail in this case

**Comment by dvviktordelev** [comment]
@dvvanessastoiber we could also unify the release.yml and release-post-merge.yml into one.

looks like [this](https://github.com/datavisyn/test-app/blob/main/.github/workflows/release.yaml) and works too

**Review by dvvanessastoiber — APPROVED** [review]
Looks good to me, thank you very much!

**Pull request merged**
